### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by uncomfyhalomacro** [fisher60/Friendo_Bot#120]
### Pagination:
- 🦝  What it does? Page by page interaction, hence its name.
- 🚀  Why we need it? So it won't consume as much space inside a thread. Pagination looks cool and keeps things tidy.
- 🙇  Who will work on it? Anyone can help. Preferably, those with more knowledge about discord bots.

**Comment by xPolar** [comment]
Hey @ReneganRonin, I've created a ton of different paginated commands before. What would you be looking for in this issue?

**Comment by fisher60** [comment]
Hello, @xPolar, we are looking for pagination with our help command. We would like to keep the help command at a manageable size and allow users to react to the help message in order to switch between help pages. The reference for this is the seasonal bot from the python discord server.

The commands/cogs should be sorted in alphabetical order. The main goal is to reduce the size of the help command by limiting results per page.

**Comment by xPolar** [comment]
Hey, been slumped with school, should be able to do this by the end of the week.
